var menuData=[
	{
		"name":"+第一级",
		"content":[
			{
				"name":"+第二级",
				"content":[
					{
						"name":"+第三级",
						"content":[
							{"name":"第四级"},
							{"name":"第四级"},
							{"name":"第四级"}
						]
					},
					{"name":"第三级"},
					{"name":"第三级"}
				]
			},
			{"name":"第二级"},
			{"name":"第二级"}
		]
	},
	{
		"name":"+第一级",
		"content":[
			{
				"name":"+第二级",
				"content":[
					{
						"name":"+第三级",
						"content":[
							{"name":"第四级"},
							{"name":"第四级"},
							{"name":"第四级"}
						]
					},
					{"name":"第三级"},
					{"name":"第三级"}
				]
			},
			{"name":"第二级"},
			{"name":"第二级"}
		]
	},
	{
		"name":"+第一级",
		"content":[
			{
				"name":"+第二级",
				"content":[
					{
						"name":"+第三级",
						"content":[
							{"name":"第四级"},
							{"name":"第四级"},
							{"name":"第四级"}
						]
					},
					{"name":"第三级"},
					{"name":"第三级"}
				]
			},
			{"name":"第二级"},
			{"name":"第二级"}
		]
	},
	{
		"name":"+第一级",
		"content":[
			{
				"name":"+第二级",
				"content":[
					{"name":"第三级"},
					{"name":"第三级"},
					{"name":"第三级"}
				]
			},
			{"name":"第二级"}
		]
	}
];
